export enum guaListEnum {
    Qian = "乾",
    Kun = "坤",
    Zhun = "屯",
    Meng = "蒙",
    Xu = "需",
    Song = "讼",
    Shi = "师",
    Bi = "比",
    XiaoXu = "小畜",
    Lü = "履",
    Tai = "泰",
    Pi = "否",
    TongRen = "同人",
    DaYou = "大有",
    Qian2 = "谦",
    Yu = "豫",
    Sui = "随",
    Gu = "蛊",
    Lin = "临",
    Guan = "观",
    ShiKe = "噬嗑",
    Ben = "贲",
    Bo = "剥",
    Fu = "复",
    WuWang = "无妄",
    DaXu = "大畜",
    Yi = "颐",
    DaGuo = "大过",
    Kan = "坎",
    Li = "离",
    Xian = "咸",
    Heng = "恒",
    Dun = "遁",
    DaZhuang = "大壮",
    Jin = "晋",
    MingYi = "明夷",
    JiaRen = "家人",
    Kui = "睽",
    Jian = "蹇",
    Jie = "解",
    Sun = "损",
    Yi2 = "益",
    Guai = "夬",
    Gou = "姤",
    Cui = "萃",
    Sheng = "升",
    Kun2 = "困",
    Jing = "井",
    Ge = "革",
    Ding = "鼎",
    Zhen = "震",
    Gen = "艮",
    Jian2 = "渐",
    Guimei = "归妹",
    Feng = "丰",
    Lv = "旅",
    Xun = "巽",
    Dui = "兑",
    Huan = "涣",
    Jie2 = "节",
    Zhongfu = "中孚",
    Xiaoguo = "小过",
    Jiji = "既济",
    Weiji = "未济"
};

export const guaBaseArray = [guaListEnum.Kun, guaListEnum.Zhen, guaListEnum.Kan, guaListEnum.Dui, guaListEnum.Gen, guaListEnum.Li, guaListEnum.Xun, guaListEnum.Qian];
export enum guaElementEnum {
    Di = "地",
    Lei = "雷",
    Shui = "水",
    Ze = "泽",
    Shan = "山",
    Huo = "火",
    Feng = "风",
    Tian = "天"
};

export enum changeYangEnum {
    one = "初九",
    two = "九二",
    three = "九三",
    four = "九四",
    five = "九五",
    six = "上九"
};
export enum changeYinEnum {
    one = "初六",
    two = "六二",
    three = "六三",
    four = "六四",
    five = "六五",
    six = "上六"
};